# Generated by Django 5.2.3 on 2025-07-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmodel',
            name='playlist_name',
            field=models.CharField(default='m'),
            preserve_default=False,
        ),
    ]
