# Generated by Django 5.2.3 on 2025-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='song_artist',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='song_name',
            field=models.CharField(max_length=100),
        ),
    ]
